# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 789f98cb04bf425b6c2a70e52d0ef58820a39c09fe965148a04e8291fca3bcd27acea7cabcb0612a6c03630e60d5adcff1608a4078572b47d04d4e6b3bb3b92b

test:
  secret_key_base: 1cf267c3b18e9151c2e5df839f0d07d0d8830abacd163faaf0f4b16124f3c5979d855dc99987b374ad77bdcc18cb59c9c039caa01fd5031799377ebbdee2e013

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
